modify script

diff --git a/bin/clean b/bin/clean
--- a/bin/clean
+++ b/bin/clean
@@ -1,4 +1,32 @@
 #!/bin/sh
+binpath=$(cd `dirname $0`; pwd)
+suc_mutex=0
+fail_mutex=0
+sitepath="${binpath}/../_site"
+if [ -d $sitepath ]; then
+    rm -fr $sitepath
+    if [ $? -eq 0 ]; then
+        suc_mutex=$[suc_mutex+1]
+        echo "\033[32;40mDelete ${sitepath} Successful... \033[0m"
+    else
+        fail_mutex=$[fail_mutex+1]
+        echo "\033[31;40mDelete ${sitepath} Fail! \033[0m"
+    fi
+fi
+deploypath="${binpath}/../_deploy"
+if [ -d $deploypath ]; then
+    rm -fr $deploypath
+    if [ $? -eq 0]; then
+        suc_mutex=$[suc_mutex+1]
+        echo "\033[32;40mDelete ${deploypath} Successful... \033[0m"
+    else
+        fail_mutex=$[fail_mutex+1]
+        echo "\033[31;40mDelete ${deploypath} Fail! \033[0m"
+    fi
+fi
 
-rm -fr _deploy
-rm -fr _site
+if [ $suc_mutex -eq 0 ] && [ $fail_mutex -eq 0 ]; then
+    echo "\033[32;40mAlready clean! \033[0m"
+elif [ $suc_mutex -gt 0 ] && [ $fail_mutex -eq 0 ]; then
+    echo "\033[32;40mClean successful! \033[0m"
+fi
diff --git a/bin/post b/bin/post
--- a/bin/post
+++ b/bin/post
@@ -1,4 +1,12 @@
 #!/bin/sh
+binpath=$(cd `dirname $0`; pwd)
+postpath="${binpath}/../_posts"
 datetime=$(date +"%Y-%m-%d-")
-filename=$datetime$1".markdown"
-touch _posts/$filename
+postname=$datetime$1".markdown"
+filename=$postpath/$postname
+touch $filename
+if [ $? -eq 0 ];then
+    echo "\033[32;40mAdd post ${filename} Successful! \033[0m"
+else
+    echo "\033[31;40mTo add ${filename} Fail! \033[0m"
+fi
